#usecase
from KingdomProject import Character, Warrior, Mage, Paladin, Building, GuardTower
my_character = Character("Ayesha")
my_character.introduce()
my_character.take_damage(45)
print(my_character.is_alive())
my_character.describe_role()
print("--" * 45)
my_warrior = Warrior("Hadiqa", "sword")
my_warrior.attack()
my_warrior.describe_role()
my_warrior.introduce()
print(my_warrior.is_alive())
print("--" * 45)
my_mage = Mage("Zara")
my_mage.cast_spell()
my_mage.describe_role()
my_mage.introduce()
print(my_mage.is_alive())
print("--" * 45)
my_paladin = Paladin("Sara", "hammer", 80)
my_paladin.introduce()
my_paladin.attack()
my_paladin.smite()
my_paladin.describe_role()
print("--" * 45)
my_building = Building(100)
my_building.repair(10)
print(my_building.durability)
print("--" * 45)
my_guard_tower = GuardTower("Ali", "spear")
my_guard_tower.attack()
my_guard_tower.repair(54)
print(my_guard_tower.durability)
